travis:
  secure:
    BINSTAR_TOKEN: CIu+shtTLrq9unj7C9Wy1E8nZvgIyiw0hto3gdtkTEOGXh0+BVVfgTf1eYzGuObrboDy3paOGNUST78O/tUvW7YodeXm14iOwue9xkoZR1k9yK1X9phIUlitd8ozDz09erzdXn2KuAVtYm8cTvWlxtmM3xeL7ipjDNJG8ybM/vBSluIH1yZXR1GncCb51Cl90kQcMA65VCGLTXRMCUtqnAIyUvTvIeKVlu5b4nTdkoKvAv20InpTeD/VDzZThIbYEJMVEDmsA3pvPVvw13XFsNL/M67w6nyurfwUJ1m/CNvptUtjVzAS501vXLXS2aEFG6eE68CV4M9IeKEPbu9FhDRVDDMsXu2y6I+vPadCBzuXvlECSLzqlcoZZRF9ycQozAfMG7ay6RNK8F3xRIt1o1VPdqspmGRp95UHTZ5mNxswu+O9nRjiv83B39K9iSFIidJEIfSVKfI4nUJNmmLjZw1riz1nGRZ25G3dgqIg7oqDa+hzDJJttURH1x8Ngs5/kSddDCUIuvcWjj4wadiVbtgcpqSv86ZNsybk8ftri+cZtJzGj0N6y0q1ep6TArsyAJut4xAkQ4a8Y31Rli2JOYj0edqGUmk4IGzSEwceZrHQyhAbTRejF7ISf9HUWUhD+NkxU/PT+V6KUXv7JOtXcyc294fPtS8teQrgbrnXU0M=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
